# Auto-loaded override file (always applied)
services:
  frontend:
    healthcheck:
      disable: true
    ports: !override
      - "3102:3000"
  postgis_db:
    ports: !override
      - "5435:5432"
