"""
Django settings for impactdb_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Try to import django-environ for environment variable management
try:
    import environ
    env = environ.Env(
        # Set casting, default value
        DEBUG=(bool, False)
    )
    # Read environment variables from .env file
    environ.Env.read_env(BASE_DIR / '.env')
except ImportError:
    # Fallback to os.environ if django-environ is not available
    env = None

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if env:
    SECRET_KEY = env('SECRET_KEY', default='django-insecure-=v1)aa*3m1()4fft5sswbu38ocuw6p7@pixvs0ot4a8p6l4luy')
else:
    SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-=v1)aa*3m1()4fft5sswbu38ocuw6p7@pixvs0ot4a8p6l4luy')

# SECURITY WARNING: don't run with debug turned on in production!
if env:
    DEBUG = env('DEBUG')
else:
    DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

if env:
    ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
else:
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.gis',  # Enable GeoDjango - uncomment when PostGIS is configured
    # 'corsheaders',  # Enable CORS for API access - uncomment when installed
    'hazard_images',  # Our main app for handling hazard images
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',  # CORS middleware should be early - uncomment when installed
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'impactdb_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'impactdb_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Temporary SQLite configuration for initial setup
# Switch to PostGIS configuration when dependencies are installed
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# PostGIS database configuration (uncomment when psycopg2 is installed)
# if env:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.contrib.gis.db.backends.postgis',
#             'NAME': env('DATABASE_NAME', default='impactdb'),
#             'USER': env('DATABASE_USER', default='postgres'),
#             'PASSWORD': env('DATABASE_PASSWORD', default='changeme'),
#             'HOST': env('DATABASE_HOST', default='localhost'),
#             'PORT': env('DATABASE_PORT', default='5432'),
#         }
#     }
# else:
#     # Fallback configuration
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.contrib.gis.db.backends.postgis',
#             'NAME': os.environ.get('DATABASE_NAME', 'impactdb'),
#             'USER': os.environ.get('DATABASE_USER', 'postgres'),
#             'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'changeme'),
#             'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
#             'PORT': os.environ.get('DATABASE_PORT', '5432'),
#         }
#     }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings for API access
if env:
    CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ])
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

# Allow all origins in development (remove in production)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# PostGIS specific settings
# This will help with spatial queries and coordinate systems
GDAL_LIBRARY_PATH = os.environ.get('GDAL_LIBRARY_PATH')
GEOS_LIBRARY_PATH = os.environ.get('GEOS_LIBRARY_PATH')
PROJ_LIB = os.environ.get('PROJ_LIB')
