# Generated by Django 5.2.5 on 2025-08-06 23:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(help_text='Latitude of the point')),
                ('longitude', models.FloatField(help_text='Longitude of the point')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Spatial Test',
                'verbose_name_plural': 'Spatial Tests',
            },
        ),
        migrations.CreateModel(
            name='HazardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the hazard image', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the hazard event')),
                ('date_captured', models.DateTimeField(help_text='Date and time when the image was captured')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the image was uploaded')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the image location', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the image location', null=True)),
                ('hazard_type', models.CharField(choices=[('FLOOD', 'Flooding'), ('CYCLONE', 'Cyclone/Hurricane'), ('EARTHQUAKE', 'Earthquake'), ('TSUNAMI', 'Tsunami'), ('FIRE', 'Wildfire'), ('DROUGHT', 'Drought'), ('LANDSLIDE', 'Landslide'), ('OTHER', 'Other')], help_text='Type of hazard depicted in the image', max_length=100)),
                ('severity_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], help_text='Severity level of the hazard', max_length=10)),
                ('image_file', models.ImageField(help_text='The hazard image file', upload_to='hazard_images/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('coordinate_system', models.CharField(default='EPSG:4326', help_text='Coordinate reference system (e.g., EPSG:4326 for WGS84)', max_length=20)),
                ('source', models.CharField(blank=True, help_text='Source of the image', max_length=255)),
                ('keywords', models.CharField(blank=True, help_text='Keywords for searching (comma-separated)', max_length=500)),
                ('quality_score', models.FloatField(blank=True, help_text='Quality score from 0.0 to 1.0', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the image is publicly accessible')),
                ('created_by', models.CharField(blank=True, help_text='User who uploaded the image', max_length=255)),
            ],
            options={
                'verbose_name': 'Hazard Image',
                'verbose_name_plural': 'Hazard Images',
                'ordering': ['-date_captured'],
                'indexes': [models.Index(fields=['hazard_type'], name='hazard_imag_hazard__d01aae_idx'), models.Index(fields=['severity_level'], name='hazard_imag_severit_9d676d_idx'), models.Index(fields=['date_captured'], name='hazard_imag_date_ca_9a03b0_idx')],
            },
        ),
    ]
